### PR TITLE
Wingspan Asia bonus cards

### PR DESCRIPTION
**Pull request by gspindles**
Updated xslx:
* Asia birds now have Notes column populated, small update on typos & bonus card column.
* Added Asia bonus cards. [Note: The Automa bonus card is in a table format, so I tentatively used `<table>`, might need css update.]

Please re-run generate new json files.

Hmm, I'm not using MS Excel, just Google Sheets.  Seems like when I download, the file size becomes smaller…

### CODE REVIEW

**Comment by gspindles** [comment]
Question, where is a good place in the UI to add beak left/right filter?
* below language, above expansion?
* below expansion, above reset?
* below food cost?
It should be 2 icons, both are on by default to show all results.

**Comment by gspindles** [comment]
Please don't merge yet. I found some typos, will push update tomorrow.

**Comment by navarog** [comment]
> Question, where is a good place in the UI to add beak left/right filter?
> 
> * below language, above expansion?
> * below expansion, above reset?
> * below food cost?
> 
> It should be 2 icons, both are on by default to show all results.

If we do the filtering by end-of-round goals, I would say the best way is to do it more properly and add all end-of-round goals to the "filtering by bonus cards" field.

**Comment by gspindles** [comment]
Fixed the typos/errors!

A lot of the goals are covered by existing filters - nests, habitat, food types, power color, vp.  While others are not really applicable (food in supply, birds in hand, egg/bird in column, no goal, cubes on play a bird, …). I do not have all of those worked out.

**Review by navarog — APPROVED** [review]

**Pull request merged**
