### PR TITLE
Add dutch translation

### PR DESCRIPTION
**Pull request by erikhuizinga**
WIP

### CODE REVIEW

**Comment by navarog** [comment]
Looking good so far

**Comment by erikhuizinga** [comment]
Note the capital Ĳ, which is a dutch glyph. If your font doesn't support it, simply use I and J as IJ.

**Comment by erikhuizinga** [comment]
Now with all bird properties!

**Comment by erikhuizinga** [comment]
No notes yet, and I'm not sure if I'm going to copy the appendix texts for them any time soone. If acceptable, please merge this PR and integrate what it provides into the application. Then open an issue for the need for dutch notes.

**Comment by navarog** [comment]
Great job! I will update the app. One small question. Should I preprocess the bird power text so the first letter is always capitalized?

**Comment by erikhuizinga** [comment]
> Should I preprocess the bird power text so the first letter is always capitalized?

On the dutch cards the first letter is never capitalized! It says e.g.:

```
ALS GEACTIVEERD: trek 2 [card].
```

Therefore I didn't capitalize the first letters, while they are full sentences. Normally in dutch a new sentence after a colon isn't capitalized. I see that the english cards do have the first letter capitalized. I suggest to keep the design and texts as close to the physical versions as possible.

**Comment by erikhuizinga** [comment]
I'm not sure if you edited the texts, but now the first letter of the power is still capitalized. However, if the power contains more than 1 sentence, the new sentences are not capitalized. That should be the other way around, e.g. (_Corvus cornix_):

Currently is:

```
EINDE RONDE: Kies 1 andere speler. voor elke actiesteen die hij op zijn [grassland] heeft, stop je 1 [card] uit je hand onder deze vogel weg. trek dan hetzelfde aantal [card].
```

Should be:

```
EINDE RONDE: kies 1 andere speler. Voor elke actiesteen die hij op zijn [grassland] heeft, stop je 1 [card] uit je hand onder deze vogel weg. Trek dan hetzelfde aantal [card].
```

**Pull request merged**
