### PR TITLE
Add some fun alternative bird art!

### PR DESCRIPTION
**Pull request by nightpool**
Hi! Me and my friend were playing Wingspan on voice the other day when we were lamenting how sad and grey the bird cards on this site were. So we came up with the idea of drawing our own, copyright free bird art that we could use on the website that wouldn't interfere with the base game. Here's what they look like:

image

I think they're pretty cute!

I've also hacked together an "asset pack" dropdown in the search form that will let users toggle between the two different types:

 &nbsp;

Happy to move this wherever you like, I was thinking about something more subtle / more of an easter-egg like requiring the users to enter the konami code or similar but decided the more straight-forward approach would be better for an initial PR. Let me know what you think!

### CODE REVIEW

**Comment by nightpool** [comment]
I still need to generate the webp files, I just haven't been at a computer with cwebp installed, will definitely work on that before merging if you're interesting in moving forward with this PR! I expect webp to do very well with compressing these files, since it works very well on contiguous blocks of color.

**Comment by navarog** [comment]
These are beautiful! 😍 I will definitely help you finish this in any way I can, I would even get rid of the silhouettes completely.

**Comment by nightpool** [comment]
Awesome! I'll let my friend Robbie know, she'll be super excited that you
like her art. Let me know if you want me to make any UI/UX changes—I can
switch the default for the dropdown, move it somewhere less prominent (if
you have any ideas?), or just remove it entirely if you think it's
unnecessary.

**Comment by navarog** [comment]
I would remove the dropdown completely and simply replace the silhouettes in the assets folder with the Robbie's images. Also, if you'd like, please give yourselves a credit under the _Special Thanks_ section in README.md and at the footer of the web app.

**Comment by navarog** [comment]
I have an update. I ran this idea by Jamey from Stonemayer Games as someone presented me with another idea with AI-generated art, and his concern is that people would confuse fan art with official art. What about then moving the drop-down to some more subtle/easter-egg location? Also, I would add to the bottom of each card that this is not official art. I will also replace the silhouettes with a generic bird image.

**Comment by navarog** [comment]
Agree and simply having it on the detail page sounds good to me!

**Comment by navarog** [comment]
Hey @nightpool, I just merged the dropdown you created, hid it a bit so that you need to write "images" into the search bar if you want the dropdown to be displayed, and added a popup with the credits and fan art disclaimer once you select the dropdown. I would still like to make Robbie's images the default one, we might still need the disclaimer text on the card detail page then. 
Let me know if you still plan to add other bird art and feel free to open another PR!

**Comment by nightpool** [comment]
Thanks Matej! I'm glad you were able to get to it, I started working on the
dropdown but unfortunately have been busy with my day job for the past few
weeks. I do believe Robbie has a backlog of more bird art that I can upload
tonight though.

**Comment by gitHu6-newb** [comment]
OMG Robbie's making more? That's fantastic!!! I love everything that everyone has done! I even love the silhouettes. My fav part of all though was spending all night trying to find how to activate the easter egg, haha I was looking right at it but glossed over it (let's say due to fatigue). I hope it's a feature that remains forever so more may enjoy the hunt.
---signed, 
random internet person who just found out about this game

**Comment by navarog** [comment]
@nightpool no problem, we can merge the Robbie's birds in batches as they come 🤗

@gitHu6-newb I like the enthusiasm! 😁

**Pull request merged**
