### PR TITLE
Add beak filter

### PR DESCRIPTION
**Pull request by gspindles**
Add beak pointing left/right filtering , placed above language filter. Feel free to move it elsewhere & update css. Has dependency on #35 to be merged & .json generated first.

* no beak filters applied - show all birds
* left beak filter on - show birds pointing left or both ways
* right beak filter on - show birds pointing right or both ways
* both filters are off - show birds facing straight

Birds facing both ways are `Common Loon` from base and `Little Grebe` from Asia.

Goals is a bigger scope update, so maybe I'll look into adding goals sheet to xlsx when I have more free time.

For wingspan numbers, is there a significance to 20cm and 150cm?

* I added back 40cm for OE's `Gray Butcherbird`, and 65cm for OE's `Wedge-Tailed Eagle`.
* 49cm for OE's `Red Wattlebird` is skipped because it's too close to 50cm (base's `Greater Roadrunner`).

Please add back 20cm and 150cm back if you'd like.

### CODE REVIEW

**Comment by gspindles** [comment]
Please update bonus card name to `Dissector` in `Pellet Dissetor` 🙁

**Review by navarog — APPROVED** [review]
This is a really great piece of work, thank you!

**Comment by gspindles** [comment]
Would you please add generation for a `goal.json` from the xslx 3rd sheet?

**Comment by navarog** [comment]
@gspindles done!

**Pull request merged**
